apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shovelmans/kubernetes.git
    targetRevision: main
    path: kubernetes/monitorizacion     # ← apunta a tu chart con values.yaml dentro
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
