apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        # ArgoCD espera admin.password en hash bcrypt
        admin.password: "{{ .ARGOCD_PASSWORD | bcrypt }}"
        # Truco: ArgoCD detecta cambio gracias a este campo
        admin.passwordMtime: "{{ now | date \"2006-01-02T15:04:05Z07:00\" }}"
  data:
    - secretKey: ARGOCD_PASSWORD
      remoteRef:
        key: secret/argocd
        property: admin-password
