apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        admin.password: "{{ .ARGOCD_HASH }}"
        admin.passwordMtime: "{{ now | date \"2006-01-02T15:04:05Z07:00\" }}"
  data:
    - secretKey: ARGOCD_HASH
      remoteRef:
        key: secret/argocd
        property: admin-password-hash
