apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shovelmans/kubernetes.git   # tu repo Git
    targetRevision: main
    path: kubernetes/portainer   # carpeta donde tienes Chart.yaml y values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    syncOptions:
      - CreateNamespace=true    # 👈 crea el namespace automáticamente
    automated:
      prune: true
      selfHeal: true
