portainer:
  service:
    type: ClusterIP
    port: 9000

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: portainer.local
        paths:
          - path: /
            pathType: Prefix
    tls: []   # sin TLS por ahora

  persistence:
    enabled: true
    storageClass: do-block-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
