adminUser: admin
adminPassword: admin

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.local
  path: /
  pathType: Prefix
  annotations: {}
  tls: false

persistence:
  enabled: true
  existingClaim: grafana-pvc

# El chart trae un Pod de tests (templates/tests/test.yaml) pensado para "helm test".
# En ArgoCD no se ejecuta y si no existe esta clave rompe al renderizar.
testFramework:
  enabled: false

# El chart puede crear un ServiceMonitor (Prometheus Operator).
# Si no usas Prometheus Operator, déjalo desactivado para evitar el mismo error.
serviceMonitor:
  enabled: false

# Algunos templates consultan .Values.serviceAccount.create.
# Define el bloque para que no sea nil.
serviceAccount:
  create: true         # o false si quieres usar una SA existente
  name: ""             # o pon el nombre de tu SA si create=false
  annotations: {}
  labels: {}
  automountServiceAccountToken: true

# Suele ser referenciado también por los templates; mejor declararlo.
rbac:
  create: true
