apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JorgeVicenteVN/kubernetes.git
    targetRevision: main
    path: kubernetes/helm/4-monitoring/3-grafana
    helm:
      releaseName: grafana
      valueFiles:
        - grafana-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
