admin:
  user: admin
  password: admin

datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: grafana.local
  path: /
  pathType: Prefix
  annotations: {}
  tls: false

persistence:
  enabled: true
  existingClaim: grafana-pvc
  storageClass: ""
  accessModes: []
  size: 5Gi

service:
  type: ClusterIP
