grafana:
  admin:
    user: admin
    password: admin

  persistence:
    enabled: true
    type: pvc
    existingClaim: grafana-pvc
    resourcePolicy: keep
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: grafana.local
    path: /
    pathType: Prefix
    tls: false

  service:
    type: ClusterIP

  config:
    useGrafanaIniFile: true
    grafanaIni:
      server:
        root_url: "%(protocol)s://%(domain)s/"
      analytics:
        reporting_enabled: false
      users:
        allow_sign_up: false
      branding:
        app_title: "Grafana GitOps 🚀"
