grafana:
  admin:
    user: admin
    password: admin

  persistence:
    enabled: true
    type: pvc
    existingClaim: grafana-pvc
    resourcePolicy: keep
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: grafana.local
    path: /
    pathType: Prefix
    tls: false

  service:
    type: NodePort   # Cambiado a NodePort para acceso directo (opcional)
    nodePorts:
      http: 32000    # Puerto externo en los nodos
