adminUser: admin
adminPassword: admin123

persistence:
  enabled: true
  type: pvc
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 32000

# Desactiva los probes que trae el chart (evita conflicto tcpSocket/httpGet)
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
