adminUser: admin
adminPassword: admin123

persistence:
  enabled: true
  type: pvc
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 32000

## Probes corregidos: solo httpGet (no tcpSocket)
livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  periodSeconds: 10
