apiVersion: v2
name: monitoring
description: Umbrella chart para kube-prometheus-stack (Prometheus, Grafana, Alertmanager, Node Exporter, etc.)
type: application
version: 0.1.0
appVersion: "1.0.0"
 
dependencies:
  - name: kube-prometheus-stack
    version: "76.2.0"   # la misma que ya tienes desplegada
    repository: "https://prometheus-community.github.io/helm-charts"