replicaCount: 1

crds:
  enabled: false

image:
  repository: grafana/grafana
  tag: 10.1.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false

persistence:
  enabled: true
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  size: 50Gi

# Montamos el secreto generado por ExternalSecrets como volumen y pasamos variables
extraVolumes:
  - name: grafana-admin-secret
    secret:
      secretName: prometheus-grafana

extraVolumeMounts:
  - name: grafana-admin-secret
    mountPath: /etc/secrets
    readOnly: true

extraEnv:
  - name: GF_SECURITY_ADMIN_USER_FILE
    value: /etc/secrets/admin-user
  - name: GF_SECURITY_ADMIN_PASSWORD_FILE
    value: /etc/secrets/admin-password

# Para desplegar el datasource de MongoDB
grafana.ini:
  plugins:
    allow_loading_unsigned_plugins: haohanyang-mongodb-datasource

extraInitContainers:
  - name: install-mongodb-community-plugin
    image: alpine:3.20
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
    command: ["/bin/sh","-lc"]
    args:
      - |
        set -euo pipefail
        apk add --no-cache curl unzip ca-certificates
        update-ca-certificates
        mkdir -p /var/lib/grafana/plugins
        rm -rf /var/lib/grafana/plugins/haohanyang-mongodb-datasource \
               /var/lib/grafana/plugins/haohanyang-mongodb-datasource-*
        URL="https://github.com/haohanyang/mongodb-datasource/releases/download/v0.3.2/haohanyang-mongodb-datasource-0.3.2.zip"
        curl -fsSL "$URL" -o /tmp/mongodb-ds.zip
        unzip -q /tmp/mongodb-ds.zip -d /var/lib/grafana/plugins/
        if [ -d /var/lib/grafana/plugins/haohanyang-mongodb-datasource-0.3.2 ]; then
          mv /var/lib/grafana/plugins/haohanyang-mongodb-datasource-0.3.2 \
             /var/lib/grafana/plugins/haohanyang-mongodb-datasource
        fi
        chown -R 472:472 /var/lib/grafana/plugins
    volumeMounts:
      - name: storage
        mountPath: /var/lib/grafana
