apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.3.1
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      values: |
        grafana:
          service:
            type: NodePort
            nodePort: 32000   # 👈 acceso a Grafana

        prometheus:
          service:
            type: ClusterIP   # ⚠️ el Operator siempre crea prometheus-operated como ClusterIP
          additionalService:
            enabled: true
            type: NodePort
            ports:
              - name: http-web
                port: 9090
                targetPort: 9090
                nodePort: 32001   # 👈 acceso a Prometheus por NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
