apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.3.1
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      valueFiles:
        - https://raw.githubusercontent.com/shovelmans/kubernetes/main/kubernetes/kubeprometheus/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
