apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.3.1
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      values: |
        grafana:
          image:
            repository: grafana/grafana
            tag: "12.1.0"
            pullPolicy: IfNotPresent

          service:
            type: ClusterIP

          persistence:
            enabled: true
            type: pvc
            existingClaim: grafana-pvc

          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.jorge.local

          # 👉 Forzar a usar tu secret
          admin:
            existingSecret: prometheus-grafana
            userKey: admin-user
            passwordKey: admin-password

          grafana.ini:
            plugins:
              allow_loading_unsigned_plugins: haohanyang-mongodb-datasource

          extraInitContainers:
            - name: install-mongodb-community-plugin
              image: alpine:3.20
              securityContext:
                runAsUser: 0
                runAsNonRoot: false
              command: ["/bin/sh","-lc"]
              args:
                - |
                  set -euo pipefail
                  apk add --no-cache curl unzip ca-certificates
                  update-ca-certificates
                  mkdir -p /var/lib/grafana/plugins
                  rm -rf /var/lib/grafana/plugins/haohanyang-mongodb-datasource \
                         /var/lib/grafana/plugins/haohanyang-mongodb-datasource-*
                  URL="https://github.com/haohanyang/mongodb-datasource/releases/download/v0.3.2/haohanyang-mongodb-datasource-0.3.2.zip"
                  curl -fsSL "$URL" -o /tmp/mongodb-ds.zip
                  unzip -q /tmp/mongodb-ds.zip -d /var/lib/grafana/plugins/
                  if [ -d /var/lib/grafana/plugins/haohanyang-mongodb-datasource-0.3.2 ]; then
                    mv /var/lib/grafana/plugins/haohanyang-mongodb-datasource-0.3.2 \
                       /var/lib/grafana/plugins/haohanyang-mongodb-datasource
                  fi
                  chown -R 472:472 /var/lib/grafana/plugins
              volumeMounts:
                - name: storage
                  mountPath: /var/lib/grafana

        prometheus:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.jorge.local
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
