apiVersion: v2
name: kube-prometheus-stack-wrapper
description: Wrapper para desplegar kube-prometheus-stack via ArgoCD
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 77.6.0   # la versión que usaste
    repository: https://prometheus-community.github.io/helm-charts
