grafana:
  service:
    type: NodePort
    nodePort: 32000
  persistence:
    enabled: true
    type: pvc
    existingClaim: grafana-pvc   # PVC que ya tienes creado

prometheus:
  service:
    type: ClusterIP
  additionalService:
    enabled: true
    type: NodePort
    ports:
      - name: http-web
        port: 9090
        targetPort: 9090
        nodePort: 32001
