grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: true
    type: pvc
    existingClaim: grafana-pvc

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.jorge.local

prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.jorge.local
