apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd   # el Application siempre en el namespace de ArgoCD
spec:
  project: agentic
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.3.1
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      valueFiles:
        - values.yaml   # 👈 aquí usamos tu values separado
  destination:
    server: https://kubernetes.default.svc
    namespace: monitorizacion
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
