adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 3000

persistence:
  enabled: true
  size: 5Gi

# Bloque correcto según el chart oficial
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
