adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 3000

persistence:
  enabled: true
  size: 5Gi

extraConfigmapMounts:
  - name: grafana-datasource
    mountPath: /etc/grafana/provisioning/datasources
    configMap: grafana-datasource
    readOnly: true
