apiVersion: v2
name: rancher-wrapper
version: 0.1.0
description: Helm wrapper chart para desplegar Rancher
dependencies:
  - name: rancher
    version: 2.8.2          # 👈 versión estable, ajusta si quieres otra
    repository: https://releases.rancher.com/server-charts/latest
