apiVersion: v2
name: prometheus-wrapper
description: "Wrapper Helm para prometheus-community/prometheus"
type: application
version: 0.1.0

dependencies:
  - name: prometheus
    version: "27.37.0"
    repository: "https://prometheus-community.github.io/helm-charts"
