apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arize-phoenix.fullname" . }}
spec:
  replicas: {{ .Values.phoenix.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "arize-phoenix.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "arize-phoenix.name" . }}
    spec:
      containers:
        - name: phoenix
          image: "{{ .Values.phoenix.image.repository }}:{{ .Values.phoenix.image.tag }}"
          imagePullPolicy: {{ .Values.phoenix.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.phoenix.service.port }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
