apiVersion: v2
name: prometheus-monitorizacion
description: Prometheus simple en ns monitorizacion
type: application
version: 0.1.0

dependencies:
  - name: prometheus
    version: 25.28.0   # versión actual estable (puedes ajustar)
    repository: https://prometheus-community.github.io/helm-charts
