alertmanager:
  enabled: true

server:
  service:
    type: ClusterIP
    port: 9090

nodeExporter:
  enabled: true
  hostNetwork: false   # evita que use red del nodo
  service:
    port: 9200
  extraArgs:
    - --web.listen-address=:9200
