nodeExporter:
  enabled: true
  hostNetwork: true
  service:
    port: 9200
  containerPort: 9200
  extraArgs: []
  extraHostPorts:
    - name: metrics
      containerPort: 9200
      hostPort: 9200
      protocol: TCP
