apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-restore   # 👈 nuevo PVC
  namespace: monitoring
spec:
  storageClassName: do-block-storage
  dataSource:
    name: grafana-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
