adminUser: admin
adminPassword: admin123

service:
  type: NodePort
  nodePort: 32000

persistence:
  enabled: true
  storageClassName: do-block-storage
  size: 2Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
