grafana:
  adminUser: admin
  adminPassword: admin123  # ⚠️ en producción usa un Secret gestionado por ArgoCD/ExternalSecrets

  service:
    type: NodePort
    nodePort: 32000
    port: 80
    targetPort: 3000

  # Datasource Prometheus provisionado automáticamente
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local
          isDefault: true

  # Sidecars para carga automática
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  # 👇 Activa persistencia (con type)
  persistence:
    type: pvc
    enabled: true
    storageClassName: do-block-storage   # usa la de tu cluster
    accessModes:
      - ReadWriteOnce
    size: 5Gi
