grafana:
  adminUser: admin
  adminPassword: admin123  # ⚠️ usa un Secret en producción

  service:
    type: ClusterIP   # ya no necesitas NodePort
    port: 80
    targetPort: 3000

  ingress:
    enabled: true
    ingressClassName: nginx   # importante, así lo recoge tu ingress-nginx
    hosts:
      - grafana.local
    path: /
    pathType: Prefix
    tls: []   # si quieres TLS, aquí metes config con cert-manager

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local
          isDefault: true
        - name: MySQL
          type: mysql
          access: proxy
          url: mysql.mysql.svc.cluster.local:3306
          database: personas
          user: root
          secureJsonData:
            password: RootPass123!
          jsonData:
            maxOpenConns: 100
            maxIdleConns: 100
            connMaxLifetime: 14400
            tlsSkipVerify: true

  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

  persistence:
    type: pvc
    enabled: true
    storageClassName: do-block-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi
