apiVersion: v2
name: kube-prometheus-stack-wrapper
description: Wrapper chart para desplegar kube-prometheus-stack desde mi repo
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 77.11.1
    repository: https://prometheus-community.github.io/helm-charts
