apiVersion: v1
kind: Service
metadata:
  name: awx-service
  namespace: awx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: awx-web
    app.kubernetes.io/part-of: awx
  ports:
    - port: 8052       # Puerto dentro del cluster
      targetPort: 8052 # Puerto del contenedor
      nodePort: 30080  # Puerto expuesto en el nodo
