# mysql-root-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-secret
  namespace: mysql
type: Opaque
stringData:
  mysql-root-password: "password-root"
  mysql-password: "password-user"
