apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shovelmans/kubernetes.git
    targetRevision: main
    path: kubernetes/mysql   # 👈 ruta a tu carpeta con los YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true   # crea el ns si no existe
      - Replace=true           # fuerza reemplazo si hay drift
    automated:
      prune: true              # elimina recursos borrados en Git
      selfHeal: true           # repara si alguien cambia algo a mano
