# Valores del subchart prometheus
prometheus:
  server:
    retention: "12h"
    service:
      type: ClusterIP   # ya no necesitamos NodePort
      port: 80

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.local
      path: /
      pathType: Prefix
      tls: []   # sin TLS, simple HTTP

    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi

  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false
