apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: grafana
    targetRevision: 12.1.8    # la versión que estás usando
    helm:
      valueFiles:
        - values.yaml         # este values debe estar en tu repo Git si lo usas desde ahí
      releaseName: grafana    # 👈 importante, que coincida con tu helm release
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring     # 👈 el mismo namespace donde ya está la release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
