service:
  type: ClusterIP
  port: 3000

persistence:
  enabled: true
  existingClaim: grafana-pvc
  storageClass: ""
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: grafana.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: false

# ⚠️ Importante:
# Como ya tienes un PVC creado a mano, NO definas admin.password aquí.
# Usa la password que ya existe en el Secret grafana-admin o resetea con grafana-cli.
