apiVersion: v2
name: vault-wrapper
description: Helm chart wrapper para desplegar Vault con mis valores
type: application
version: 0.1.0

dependencies:
  - name: vault
    version: 0.29.1   # 👈 versión con soporte para ingress en UI
    repository: https://helm.releases.hashicorp.com
