server:
  dev:
    enabled: true

  # Habilita la creación de un recurso Ingress para el API y la UI
  ingress:
    enabled: true
    ingressClassName: nginx        # usa tu controlador nginx
    activeService: true            # true = apunta a vault-active (en HA) / vault en dev
    hosts:
      - host: vault.jorge.local
        paths:
          - path: /
            pathType: Prefix

ui:
  enabled: true
  serviceType: ClusterIP
