server:
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: do-block-storage-retain

  ha:
    enabled: false     # modo standalone simple
  standalone:
    enabled: true

  service:
    type: NodePort
    nodePort: 32000

injector:
  enabled: true
