server:
  dev:
    enabled: true

  # Ingress para exponer Vault (API y UI) a través de tu NGINX
  ingress:
    enabled: true
    ingressClassName: nginx
    activeService: true      # se usa vault-active en HA, y vault en modo dev
    hosts:
      - host: vault.jorge.local
        paths:
          - path: /
            pathType: Prefix

ui:
  enabled: true
  serviceType: ClusterIP
