crds:
  enabled: false

kubeEtcd: { enabled: false }
kubeControllerManager: { enabled: false }
kubeScheduler: { enabled: false }
kubeProxy: { enabled: false }

prometheus:
  service:
    type: NodePort
    nodePort: 32090
  prometheusSpec:
    retention: 12h
    scrapeInterval: 60s
    resources:
      requests: { cpu: 200m, memory: 400Mi }
      limits:   { cpu: 500m, memory: 800Mi }
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    existingClaim: grafana-pvc
  service:
    type: NodePort
    nodePort: 32081
  resources:
    requests: { cpu: 100m, memory: 150Mi }
    limits:   { cpu: 300m, memory: 300Mi }

alertmanager:
  alertmanagerSpec:
    resources:
      requests: { cpu: 50m, memory: 100Mi }
      limits:   { cpu: 200m, memory: 200Mi }
  service:
    type: ClusterIP

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
