apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd   # donde corre ArgoCD
spec:
  project: default
  source:
    repoURL: https://github.com/shovelmans/kubernetes.git
    targetRevision: main
    path: kubernetes/jenkins   # <--- apunta a la carpeta del chart
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins         # <--- namespace donde quieres Jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
