apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-release1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami   # Chart oficial
    chart: apache
    targetRevision: 11.4.29                      # Versión exacta
    helm:
      releaseName: apache-release1
      valueFiles:
        - values.yaml                            # Tus valores
  destination:
    server: https://kubernetes.default.svc
    namespace: apache
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
