grafana:
  adminUser: admin
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000

prometheus:
  service:
    type: NodePort
    nodePort: 32001

alertmanager:
  service:
    type: NodePort
    nodePort: 32002
